apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: sample-job-placement
  namespace: default
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: name
              operator: In
              values:
                - cluster1
                - cluster2
                - cluster3
